server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:13406/thermal_comfort?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 201911080162fwl
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool

  data:
    redis:
      host: 127.0.0.1
      port: 16379

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.wanling.backend.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
